(function(){
if(document.getElementById('ccRecentV19'))return;
const script=document.currentScript; const base=new URL('./',script.src);
const area=(script.dataset.area||'최근 현장').trim();
const nearby=(script.dataset.nearby||area).split('|').filter(Boolean).slice(0,6); while(nearby.length<6)nearby.push(area);
function A(p){return new URL(p,base).href} function md(i){let d=new Date();d.setDate(d.getDate()-i);return (d.getMonth()+1)+'/'+d.getDate()}
const sec=document.createElement('section');sec.id='ccRecentV19';sec.innerHTML='<div class="ccr19-head"><h2>최근 청소 전후</h2><p>최근 작업 현장을 사진과 영상으로 확인해보세요.</p></div><div class="ccr19-strip"></div>';
let live=document.querySelector('.live-box,.cc-live-wrap,.cc-live-estimate-final,#cc-live-estimate-final,[class*="live-estimate"],[id*="live-estimate"]');
if(!live){for(const el of document.querySelectorAll('section,div')){if((el.textContent||'').includes('실시간 견적문의')){live=el;break;}}}
if(live) live.insertAdjacentElement('afterend',sec); else {const main=document.querySelector('main'); if(main)main.insertAdjacentElement('beforeend',sec); else document.body.appendChild(sec)}
const modal=document.createElement('div');modal.className='ccr19-modal';modal.innerHTML='<div class="ccr19-shell"><button class="ccr19-x" type="button">×</button><div class="ccr19-hero"><img class="ccr19-big" alt="최근 청소 전후"></div><div class="ccr19-body"><h2 class="ccr19-title"></h2><div class="ccr19-meta"></div><div class="ccr19-tags"><span>#청소전후</span><span>#체인지클린</span><span>#최근현장</span></div><p>최근 청소 전후 사진과 영상으로 작업 결과를 확인해보세요.</p><div class="ccr19-actions"><button class="ccr19-video-btn" type="button">▶ 영상 보기</button><button class="ccr19-est-btn" type="button">⚡ 빠른 견적문의</button></div></div></div>';document.body.appendChild(modal);
const vf=document.createElement('div');vf.className='ccr19-video';vf.innerHTML='<button class="ccr19-vx" type="button">×</button><img class="ccr19-logo" src="'+A('changeclean_logo.png')+'" alt="체인지클린"><video class="ccr19-player" playsinline controls preload="metadata"></video><button class="ccr19-video-est" type="button">⚡ 빠른 견적 바로가기</button>';document.body.appendChild(vf);
const strip=sec.querySelector('.ccr19-strip'); let cur=0;
nearby.forEach((name,i)=>{let b=document.createElement('button');b.type='button';b.className='ccr19-card';b.innerHTML='<div class="ccr19-thumb"><img src="'+A('recent_'+String(i+1).padStart(2,'0')+'.webp')+'" alt="'+name+' 최근 청소 전후"><span class="ccr19-date">'+md(i)+'</span><span class="ccr19-play">▶</span></div><div class="ccr19-info"><b>'+name+' 최근 청소 전후</b><span>체인지클린 최근 현장</span></div>';b.onclick=()=>openCard(i);strip.appendChild(b)});
function openCard(i){cur=i;modal.querySelector('.ccr19-big').src=A('recent_'+String(i+1).padStart(2,'0')+'.webp');modal.querySelector('.ccr19-title').textContent=nearby[i]+' 최근 청소 전후';modal.querySelector('.ccr19-meta').textContent=area+' · '+md(i);modal.classList.add('on')}
function goEstimate(){modal.classList.remove('on');closeV();let e=document.querySelector('#estimate-form,#estimate,.form');if(e)e.scrollIntoView({behavior:'smooth',block:'start'});else location.href='tel:01068113176'}
const player=vf.querySelector('.ccr19-player');function openV(){const day=Math.floor(Date.now()/86400000);const n=((cur+day)%10)+1;player.src=A('videos10/clean_'+String(n).padStart(2,'0')+'.mp4');vf.classList.add('on');player.currentTime=0;player.play().catch(()=>{})}function closeV(){player.pause();vf.classList.remove('on')}
modal.querySelector('.ccr19-x').onclick=()=>modal.classList.remove('on');modal.querySelector('.ccr19-video-btn').onclick=openV;modal.querySelector('.ccr19-est-btn').onclick=goEstimate;vf.querySelector('.ccr19-vx').onclick=closeV;vf.querySelector('.ccr19-video-est').onclick=goEstimate;modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('on')});vf.addEventListener('click',e=>{if(e.target===vf)closeV()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){modal.classList.remove('on');closeV()}});
})();